{"name": "Login con credenciales correctas -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".bm-burger-button\"}\n  (Session info: chrome=97.0.4692.99)\nStacktrace:\n0   chromedriver                        0x00000001101efe69 chromedriver + 5160553\n1   chromedriver                        0x000000011017a593 chromedriver + 4679059\n2   chromedriver                        0x000000010fd2e2c8 chromedriver + 172744\n3   chromedriver                        0x000000010fd63b62 chromedriver + 392034\n4   chromedriver                        0x000000010fd63d21 chromedriver + 392481\n5   chromedriver                        0x000000010fd96304 chromedriver + 598788\n6   chromedriver                        0x000000010fd813fd chromedriver + 513021\n7   chromedriver                        0x000000010fd940ab chromedriver + 589995\n8   chromedriver                        0x000000010fd81623 chromedriver + 513571\n9   chromedriver                        0x000000010fd56dce chromedriver + 339406\n10  chromedriver                        0x000000010fd58105 chromedriver + 344325\n11  chromedriver                        0x00000001101ab23e chromedriver + 4878910\n12  chromedriver                        0x00000001101c2d17 chromedriver + 4975895\n13  chromedriver                        0x00000001101c8a3f chromedriver + 4999743\n14  chromedriver                        0x00000001101c361a chromedriver + 4978202\n15  chromedriver                        0x000000011019fbb1 chromedriver + 4832177\n16  chromedriver                        0x00000001101dffd8 chromedriver + 5095384\n17  chromedriver                        0x00000001101e0161 chromedriver + 5095777\n18  chromedriver                        0x00000001101f72a8 chromedriver + 5190312\n19  libsystem_pthread.dylib             0x00007ff81fe3a4f4 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81fe3600f thread_start + 15\n\n", "trace": "  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/LoginTests.py\", line 25, in step_impl\n    mensaje_error = context.web.find_element(By.CLASS_NAME, elemento)\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1244, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643928536877, "stop": 1643928539373}, {"name": "When se lanza el login con \"locked_out_user\" y \"secret_sauce\"", "status": "passed", "start": 1643928539374, "stop": 1643928539748}, {"name": "Then aparece \"bm-burger-button\" en pantalla", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".bm-burger-button\"}\n  (Session info: chrome=97.0.4692.99)\nStacktrace:\n0   chromedriver                        0x00000001101efe69 chromedriver + 5160553\n1   chromedriver                        0x000000011017a593 chromedriver + 4679059\n2   chromedriver                        0x000000010fd2e2c8 chromedriver + 172744\n3   chromedriver                        0x000000010fd63b62 chromedriver + 392034\n4   chromedriver                        0x000000010fd63d21 chromedriver + 392481\n5   chromedriver                        0x000000010fd96304 chromedriver + 598788\n6   chromedriver                        0x000000010fd813fd chromedriver + 513021\n7   chromedriver                        0x000000010fd940ab chromedriver + 589995\n8   chromedriver                        0x000000010fd81623 chromedriver + 513571\n9   chromedriver                        0x000000010fd56dce chromedriver + 339406\n10  chromedriver                        0x000000010fd58105 chromedriver + 344325\n11  chromedriver                        0x00000001101ab23e chromedriver + 4878910\n12  chromedriver                        0x00000001101c2d17 chromedriver + 4975895\n13  chromedriver                        0x00000001101c8a3f chromedriver + 4999743\n14  chromedriver                        0x00000001101c361a chromedriver + 4978202\n15  chromedriver                        0x000000011019fbb1 chromedriver + 4832177\n16  chromedriver                        0x00000001101dffd8 chromedriver + 5095384\n17  chromedriver                        0x00000001101e0161 chromedriver + 5095777\n18  chromedriver                        0x00000001101f72a8 chromedriver + 5190312\n19  libsystem_pthread.dylib             0x00007ff81fe3a4f4 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81fe3600f thread_start + 15\n\n", "trace": "  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/LoginTests.py\", line 25, in step_impl\n    mensaje_error = context.web.find_element(By.CLASS_NAME, elemento)\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1244, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/manuelgonzalezcosta/Documents/Master/profundizacion/selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1643928539749, "stop": 1643928539771}], "parameters": [{"name": "usuario", "value": "locked_out_user"}, {"name": "contrasena", "value": "secret_sauce"}, {"name": "elemento", "value": "bm-burger-button"}], "start": 1643928536876, "stop": 1643928539771, "uuid": "9ea44790-252d-4daf-819e-dea96d4d3fe1", "historyId": "be90b77c9e444a6acc727fa62b53b747", "fullName": "Pruebas sobre el login: Login con credenciales correctas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}